### ISSUE TITLE
Problem with Elixir

### ISSUE THREAD

**Issue by dev-cyprium** [inch-ci/inch_ci-web#233]
```                         Adding project to Inch CI ...                          

** (InchEx.Docs.Retriever.Error) module ExTrails.Application was not compiled with flag --docs
    lib/inch_ex/docs/retriever.ex:83: InchEx.Docs.Retriever.verify_module/1
    lib/inch_ex/docs/retriever.ex:72: InchEx.Docs.Retriever.get_module/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    lib/inch_ex/docs/retriever.ex:51: InchEx.Docs.Retriever.docs_from_modules/2
    lib/inch_ex.ex:39: InchEx.generate_docs/4
    lib/mix/tasks/inch.ex:48: Mix.Tasks.Inch.run/4
    lib/mix/tasks/inchci_add.ex:28: Mix.Tasks.Inchci.Add.add_to_inch_ci/0
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
```

**Comment by dev-cyprium** [comment]
I get that by running `MIX_ENV=docs mix do deps.get, inchci.add`
